/**
 * Invoicex Copyright (c) 2005,2006,2007,2008,2009 Marco Ceccarelli, Tnx snc
 *
 * Questo software Ã¨ soggetto, e deve essere distribuito con la licenza GNU
 * General Public License, Version 2. La licenza accompagna il software o potete
 * trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the GNU General
 * Public License, Version 2. The license should have accompanied the software
 * or you may obtain a copy of the license from the Free Software Foundation at
 * http://www.fsf.org .
 *
 * -- Marco Ceccarelli (m.ceccarelli@tnx.it) Tnx snc (http://www.tnx.it)
 *
 */
package it.tnx.invoicex.gui;

import it.tnx.commons.SwingUtils;
import java.awt.Frame;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import org.jdesktop.jdic.desktop.Desktop;
import org.jdesktop.jdic.desktop.Message;

/**
 *
 * @author test1
 */
public class JDialogAbout extends javax.swing.JDialog {

    public JDialogAbout(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();

        File logover = new File("img/logover.png");
        if (logover.exists()) {
            labLogo.setIcon(new javax.swing.ImageIcon(logover.getAbsolutePath()));
        } else {
            labLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/logo.jpg")));
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXHyperlink12 = new org.jdesktop.swingx.JXHyperlink();
        jLabel6 = new javax.swing.JLabel();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jLabel3 = new javax.swing.JLabel();
        jXHyperlink11 = new org.jdesktop.swingx.JXHyperlink();
        jLabel4 = new javax.swing.JLabel();
        jXHyperlink3 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink4 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink5 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink6 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink7 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink8 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink9 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink10 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink13 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink14 = new org.jdesktop.swingx.JXHyperlink();
        jLabel7 = new javax.swing.JLabel();
        jXHyperlink15 = new org.jdesktop.swingx.JXHyperlink();
        jLabel8 = new javax.swing.JLabel();
        jXHyperlink16 = new org.jdesktop.swingx.JXHyperlink();
        jLabel9 = new javax.swing.JLabel();
        jXHyperlink17 = new org.jdesktop.swingx.JXHyperlink();
        jLabel10 = new javax.swing.JLabel();
        jXHyperlink18 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink19 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink20 = new org.jdesktop.swingx.JXHyperlink();
        jLabel11 = new javax.swing.JLabel();
        jXHyperlink21 = new org.jdesktop.swingx.JXHyperlink();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jXHyperlink22 = new org.jdesktop.swingx.JXHyperlink();
        jLabel14 = new javax.swing.JLabel();
        jXHyperlink23 = new org.jdesktop.swingx.JXHyperlink();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jXHyperlink25 = new org.jdesktop.swingx.JXHyperlink();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jXHyperlink24 = new org.jdesktop.swingx.JXHyperlink();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jXHyperlink26 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink27 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink28 = new org.jdesktop.swingx.JXHyperlink();
        jLabel23 = new javax.swing.JLabel();
        jXHyperlink29 = new org.jdesktop.swingx.JXHyperlink();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informazioni");

        labLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setText("Il programma");

        jXHyperlink12.setText("Invoicex");
        jXHyperlink12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink12ActionPerformed(evt);
            }
        });

        jLabel6.setText(" è ideato e realizzato da:");

        jXHyperlink1.setText("TNX srl");
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink1ActionPerformed(evt);
            }
        });

        jLabel3.setText("I sorgenti di Invoicex Base sono in licenza");

        jXHyperlink11.setText("GPL v2");
        jXHyperlink11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink11ActionPerformed(evt);
            }
        });

        jLabel4.setText("Invoicex utilizza le seguenti librerie open source:");

        jXHyperlink3.setText("Apache Commons");
        jXHyperlink3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink3ActionPerformed(evt);
            }
        });

        jXHyperlink4.setText("JGoodies");
        jXHyperlink4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink4ActionPerformed(evt);
            }
        });

        jXHyperlink5.setText("IText");
        jXHyperlink5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink5ActionPerformed(evt);
            }
        });

        jXHyperlink6.setText("Jasper Reports");
        jXHyperlink6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink6ActionPerformed(evt);
            }
        });

        jXHyperlink7.setText("JDIC");
        jXHyperlink7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink7ActionPerformed(evt);
            }
        });

        jXHyperlink8.setText("JFreeChart");
        jXHyperlink8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink8ActionPerformed(evt);
            }
        });

        jXHyperlink9.setText("Mysql");
        jXHyperlink9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink9ActionPerformed(evt);
            }
        });

        jXHyperlink10.setText("Swingx");
        jXHyperlink10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink10ActionPerformed(evt);
            }
        });

        jXHyperlink13.setText("mjpf");
        jXHyperlink13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink13ActionPerformed(evt);
            }
        });

        jXHyperlink14.setText("Tango icons");
        jXHyperlink14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink14ActionPerformed(evt);
            }
        });

        jLabel7.setText("Ringraziamo per i contributi al progetto:");

        jXHyperlink15.setText("Samuele Innocenti");
        jXHyperlink15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink15ActionPerformed(evt);
            }
        });

        jLabel8.setText("(correzioni database e sviluppo installer linux)");

        jXHyperlink16.setText("Giovanni Derks ");
        jXHyperlink16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink16ActionPerformed(evt);
            }
        });

        jLabel9.setText("(aggiunta flag numerazione fatture pro-forma)");

        jXHyperlink17.setText("Lorenzo Piccinini");
        jXHyperlink17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink17ActionPerformed(evt);
            }
        });

        jLabel10.setText("(funzione duplica documenti, inseirmento prezzo ivato)");

        jXHyperlink18.setText("TonicLF");
        jXHyperlink18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink18ActionPerformed(evt);
            }
        });

        jXHyperlink19.setText("OfficeLnFs");
        jXHyperlink19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink19ActionPerformed(evt);
            }
        });

        jXHyperlink20.setText("Mario Neè");
        jXHyperlink20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink20ActionPerformed(evt);
            }
        });

        jLabel11.setText("(migliorie nella gestione delle connessioni a Mysql ed altri bug fixing)");

        jXHyperlink21.setText("Alessio Toce");
        jXHyperlink21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink21ActionPerformed(evt);
            }
        });

        jLabel12.setText("(sviluppo e bug fixing)");

        jLabel13.setText("Un ringraziamento particolare a:");

        jXHyperlink22.setText("Claudio Romeo");
        jXHyperlink22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink22ActionPerformed(evt);
            }
        });

        jLabel14.setText("di");

        jXHyperlink23.setText("Studio Rosa Pristina");
        jXHyperlink23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink23ActionPerformed(evt);
            }
        });

        jLabel15.setText("per la redazione del manuale completo di Invoicex");

        jLabel16.setText("e le varie segnalazioni di bugs e migliorie da apportare");

        jLabel1.setText("e alcune icone da ");

        jXHyperlink25.setText("www.iconsmind.com");
        jXHyperlink25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink25ActionPerformed(evt);
            }
        });

        jLabel17.setText("I sorgenti delle funzionalità aggiuntive delle versioni Professional,");

        jLabel18.setText("Professional Plus ed Enterprise sono in ");

        jXHyperlink24.setText("licenza TNX");
        jXHyperlink24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink24ActionPerformed(evt);
            }
        });

        jLabel19.setText("- Viale Marconi 111/A - 53036 Poggibonsi (SI) - Italy");

        jLabel20.setText("Codice fiscale e Partita IVA 05080080483 - iscritta al registro delle imprese di Siena");

        jLabel21.setText("Numero REA 116347 - Capitale sociale versato € 12.000,00");

        jLabel22.setText("Posta certificata certificata@pec.tnx.it");

        jLabel5.setText("e da ");

        jXHyperlink26.setText("");
        jXHyperlink26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink26ActionPerformed(evt);
            }
        });

        jXHyperlink27.setText("");
        jXHyperlink27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink27ActionPerformed(evt);
            }
        });

        jXHyperlink28.setText("icons8.com");
        jXHyperlink28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink28ActionPerformed(evt);
            }
        });

        jLabel23.setText("... ed un grazie a tutti gli utilizzatori che ci segnalano bugs o migliorie da implementare !");

        jXHyperlink29.setText("Apache POI");
        jXHyperlink29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink29ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labLogo)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel4)
                    .add(layout.createSequentialGroup()
                        .add(jXHyperlink3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jXHyperlink5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jXHyperlink6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jXHyperlink7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jXHyperlink8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jXHyperlink9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jXHyperlink10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jXHyperlink13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel17)
                    .add(layout.createSequentialGroup()
                        .add(jLabel18)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jXHyperlink24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel13)
                    .add(jLabel7)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel16)
                            .add(layout.createSequentialGroup()
                                .add(jXHyperlink22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel14)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jXHyperlink23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel15))
                            .add(layout.createSequentialGroup()
                                .add(jXHyperlink16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(5, 5, 5)
                                .add(jLabel9))
                            .add(layout.createSequentialGroup()
                                .add(jXHyperlink15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(5, 5, 5)
                                .add(jLabel8))
                            .add(layout.createSequentialGroup()
                                .add(jXHyperlink17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel10))
                            .add(layout.createSequentialGroup()
                                .add(jXHyperlink20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel11))
                            .add(layout.createSequentialGroup()
                                .add(jXHyperlink21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel12))
                            .add(jLabel23)))
                    .add(layout.createSequentialGroup()
                        .add(jXHyperlink1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel19))
                    .add(jLabel20)
                    .add(jLabel21)
                    .add(jLabel22))
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(314, Short.MAX_VALUE)
                    .add(jXHyperlink27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(178, 178, 178)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(labLogo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jXHyperlink12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jXHyperlink1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel19))
                .add(2, 2, 2)
                .add(jLabel20)
                .add(2, 2, 2)
                .add(jLabel21)
                .add(2, 2, 2)
                .add(jLabel22)
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jXHyperlink11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(2, 2, 2)
                .add(jLabel17)
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18)
                    .add(jXHyperlink24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel4)
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jXHyperlink3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jXHyperlink6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jXHyperlink29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jXHyperlink7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jXHyperlink18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(jXHyperlink25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(jXHyperlink26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jXHyperlink13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel13)
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jXHyperlink22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14)
                    .add(jXHyperlink23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15))
                .add(1, 1, 1)
                .add(jLabel16)
                .add(18, 18, 18)
                .add(jLabel7)
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jXHyperlink15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jXHyperlink16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jXHyperlink17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jXHyperlink20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jXHyperlink21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .add(2, 2, 2)
                .add(jLabel23)
                .addContainerGap(27, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(249, Short.MAX_VALUE)
                    .add(jXHyperlink27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(189, 189, 189)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXHyperlink12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink12ActionPerformed
        try {
//            SwingUtils.openUrl(new URL("http://www.tnx.it/index.php?p=progetto_invoicex&l=ita"));
            SwingUtils.openUrl(new URL("http://www.invoicex.it/fatture/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink12ActionPerformed

    private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.tnx.it"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void jXHyperlink11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink11ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.softwarelibero.it/documentazione/softwarelibero.shtml"));
            //SwingUtils.openUrl(new URL("http://www.softwarelibero.it/gnudoc/gpl.it.txt"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink11ActionPerformed

    private void jXHyperlink3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink3ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://jakarta.apache.org/commons/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink3ActionPerformed

    private void jXHyperlink4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink4ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.jgoodies.com/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink4ActionPerformed

    private void jXHyperlink5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink5ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.lowagie.com/iText/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink5ActionPerformed

    private void jXHyperlink6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink6ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://jasperforge.org/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink6ActionPerformed

    private void jXHyperlink7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink7ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://jdic.dev.java.net/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink7ActionPerformed

    private void jXHyperlink8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink8ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.jfree.org/jfreechart/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink8ActionPerformed

    private void jXHyperlink9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink9ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.mysql.com/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink9ActionPerformed

    private void jXHyperlink10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink10ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://swinglabs.org/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink10ActionPerformed

    private void jXHyperlink13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink13ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://mjpfproject.googlepages.com/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink13ActionPerformed

    private void jXHyperlink14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink14ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://tango.freedesktop.org/Tango_Desktop_Project"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink14ActionPerformed

    private void jXHyperlink15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink15ActionPerformed
        try {
            Message m = new Message();
            m.setSubject("Invoicex");
            List addr = new ArrayList();
            addr.add("samuele.innocenti@gmail.com");
            m.setToAddrs(addr);
            Desktop.mail(m);
        } catch (Exception err) {
            err.printStackTrace();
            try {
                SwingUtils.openUrl(new URL("mailto:samuele.innocenti@gmail.com"));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jXHyperlink15ActionPerformed

    private void jXHyperlink16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink16ActionPerformed
        try {
            Message m = new Message();
            m.setSubject("Invoicex");
            List addr = new ArrayList();
            addr.add("virtualdarkness@gmail.com");
            m.setToAddrs(addr);
            Desktop.mail(m);
        } catch (Exception err) {
            err.printStackTrace();
            try {
                SwingUtils.openUrl(new URL("mailto:virtualdarkness@gmail.com"));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jXHyperlink16ActionPerformed

    private void jXHyperlink17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink17ActionPerformed
        try {
            Message m = new Message();
            m.setSubject("Invoicex");
            List addr = new ArrayList();
            addr.add("l.piccinini@tnx.it");
            m.setToAddrs(addr);
            Desktop.mail(m);
        } catch (Exception err) {
            err.printStackTrace();
            try {
                SwingUtils.openUrl(new URL("mailto:l.piccinini@tnx.it"));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jXHyperlink17ActionPerformed

    private void jXHyperlink18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink18ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.digitprop.com/tonic/tonic.php"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink18ActionPerformed

    private void jXHyperlink19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink19ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://officelnfs.sourceforge.net/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink19ActionPerformed

    private void jXHyperlink20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink20ActionPerformed
        try {
            Message m = new Message();
            m.setSubject("Invoicex");
            List addr = new ArrayList();
            addr.add("mario.nee@softfour.com");
            m.setToAddrs(addr);
            Desktop.mail(m);
        } catch (Exception err) {
            err.printStackTrace();
            try {
                SwingUtils.openUrl(new URL("mailto:mario.nee@softfour.com"));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jXHyperlink20ActionPerformed

    private void jXHyperlink21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink21ActionPerformed
        try {
            Message m = new Message();
            m.setSubject("Invoicex");
            List addr = new ArrayList();
            addr.add("a.toce@tnx.it");
            m.setToAddrs(addr);
            Desktop.mail(m);
        } catch (Exception err) {
            err.printStackTrace();
            try {
                SwingUtils.openUrl(new URL("mailto:a.toce@tnx.it"));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jXHyperlink21ActionPerformed

    private void jXHyperlink22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink22ActionPerformed
        try {
            Message m = new Message();
            m.setSubject("Invoicex");
            List addr = new ArrayList();
            addr.add("studio@studiorosapristina.it");
            m.setToAddrs(addr);
            Desktop.mail(m);
        } catch (Exception err) {
            err.printStackTrace();
            try {
                SwingUtils.openUrl(new URL("mailto:studio@studiorosapristina.it"));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jXHyperlink22ActionPerformed

    private void jXHyperlink23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink23ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.studiorosapristina.it/"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink23ActionPerformed

    private void jXHyperlink25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink25ActionPerformed
        try {
            SwingUtils.openUrl(new URL("https://www.iconsmind.com"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink25ActionPerformed

    private void jXHyperlink24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink24ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.invoicex.it/_pagine/licenza_tnx.html"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jXHyperlink24ActionPerformed

    private void jXHyperlink26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXHyperlink26ActionPerformed

    private void jXHyperlink27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXHyperlink27ActionPerformed

    private void jXHyperlink28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink28ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://icons8.com/"));
        } catch (Exception err) {
            err.printStackTrace();
        }        
    }//GEN-LAST:event_jXHyperlink28ActionPerformed

    private void jXHyperlink29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink29ActionPerformed
        try {
            SwingUtils.openUrl(new URL("https://poi.apache.org/"));
        } catch (Exception err) {
            err.printStackTrace();
        }        
    }//GEN-LAST:event_jXHyperlink29ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink10;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink11;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink12;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink13;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink14;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink15;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink16;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink17;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink18;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink19;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink20;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink21;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink22;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink23;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink24;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink25;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink26;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink27;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink28;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink29;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink4;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink5;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink6;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink7;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink8;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink9;
    private javax.swing.JLabel labLogo;
    // End of variables declaration//GEN-END:variables
}
