/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.tnx.invoicex.gui;

import com.webbyit.swing.ModalityInternalFrame;
import it.tnx.Db;
import it.tnx.commons.DebugFastUtils;
import it.tnx.commons.SwingUtils;
import it.tnx.commons.cu;
import it.tnx.commons.dbu;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import org.apache.commons.lang.StringUtils;
import tnxbeans.tnxDbPanel;

/**
 *
 * @author Marco
 */
public class JInternalFrameContatto extends ModalityInternalFrame {
    private String dbStato;
    private Integer id_row_model = null;

    /**
     * Creates new form JInternalFrameContatto
     */
    public JInternalFrameContatto() {
        initComponents();
        myinit();
    }

    public JInternalFrameContatto(JComponent parent) {
        super(parent);
        initComponents();
        myinit();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dati = new tnxbeans.tnxDbPanel();
        comTipo = new tnxbeans.tnxComboField();
        texNome = new tnxbeans.tnxTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        texTel = new tnxbeans.tnxTextField();
        texEmail = new tnxbeans.tnxTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        chePrevVen = new tnxbeans.tnxCheckBox();
        cheOrdiVen = new tnxbeans.tnxCheckBox();
        cheDDTVen = new tnxbeans.tnxCheckBox();
        cheFattVen = new tnxbeans.tnxCheckBox();
        cheOrdiAcq = new tnxbeans.tnxCheckBox();
        cheDDTAcq = new tnxbeans.tnxCheckBox();
        chePrevAcq = new tnxbeans.tnxCheckBox();
        cheFattAcq = new tnxbeans.tnxCheckBox();
        cheSolleciti = new tnxbeans.tnxCheckBox();
        butAnnulla = new javax.swing.JButton();
        butConferma = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        texNote = new tnxbeans.tnxMemoField();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Dettaglio contatto");

        comTipo.setDbNomeCampo("tipo");
        comTipo.setDbRiempireForceText(true);
        comTipo.setDbSalvaKey(false);

        texNome.setColumns(40);
        texNome.setDbNomeCampo("nome");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tipo");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nome");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Telefono");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email");

        texTel.setColumns(40);
        texTel.setDbNomeCampo("telefono");

        texEmail.setColumns(40);
        texEmail.setDbNomeCampo("email");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/Checked Checkbox-16.png"))); // NOI18N
        jButton1.setToolTipText("Seleziona tutti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/Unchecked Checkbox-16.png"))); // NOI18N
        jButton2.setToolTipText("Deseleziona tutti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Includi nell'invio email per");

        chePrevVen.setText("Preventivi Vendita");
        chePrevVen.setDbNomeCampo("invia_email_prev_ven");

        cheOrdiVen.setText("Ordini Vendita");
        cheOrdiVen.setDbNomeCampo("invia_email_ordi_ven");

        cheDDTVen.setText("DDT Vendita");
        cheDDTVen.setDbNomeCampo("invia_email_ddt_ven");

        cheFattVen.setText("Fatture Vendita");
        cheFattVen.setDbNomeCampo("invia_email_fatt_ven");

        cheOrdiAcq.setText("Ordini Acquisto");
        cheOrdiAcq.setDbNomeCampo("invia_email_ordi_acq");

        cheDDTAcq.setText("DDT Acquisto");
        cheDDTAcq.setDbNomeCampo("invia_email_ddt_acq");

        chePrevAcq.setText("Preventivi Acquisto");
        chePrevAcq.setDbDescCampo("");
        chePrevAcq.setDbNomeCampo("invia_email_prev_acq");

        cheFattAcq.setText("Fatture Acquisto");
        cheFattAcq.setDbNomeCampo("invia_email_fatt_acq");

        cheSolleciti.setText("Solleciti di pagamento");
        cheSolleciti.setDbNomeCampo("invia_email_sollecito");
        cheSolleciti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        butAnnulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/Delete Sign-16.png"))); // NOI18N
        butAnnulla.setText("Annulla");
        butAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnullaActionPerformed(evt);
            }
        });

        butConferma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/Checkmark-16.png"))); // NOI18N
        butConferma.setText("Conferma");
        butConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfermaActionPerformed(evt);
            }
        });

        texNote.setDbNomeCampo("note");

        jLabel6.setText("Note");

        org.jdesktop.layout.GroupLayout datiLayout = new org.jdesktop.layout.GroupLayout(dati);
        dati.setLayout(datiLayout);
        datiLayout.setHorizontalGroup(
            datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(datiLayout.createSequentialGroup()
                .addContainerGap()
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, texNote, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, datiLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(butAnnulla)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(butConferma))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1)
                    .add(datiLayout.createSequentialGroup()
                        .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(datiLayout.createSequentialGroup()
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(texTel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(datiLayout.createSequentialGroup()
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(comTipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(datiLayout.createSequentialGroup()
                                .add(jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(texNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(datiLayout.createSequentialGroup()
                                .add(jLabel10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(texEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel6)
                            .add(datiLayout.createSequentialGroup()
                                .add(11, 11, 11)
                                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, datiLayout.createSequentialGroup()
                                        .add(jButton1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jButton2))
                                    .add(jLabel5))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, chePrevVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, cheOrdiVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, cheDDTVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, cheFattVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(24, 24, 24)
                                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(cheOrdiAcq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(cheDDTAcq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(cheFattAcq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(datiLayout.createSequentialGroup()
                                        .add(chePrevAcq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(cheSolleciti, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        datiLayout.linkSize(new java.awt.Component[] {jLabel10, jLabel7, jLabel8, jLabel9}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        datiLayout.setVerticalGroup(
            datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, datiLayout.createSequentialGroup()
                .addContainerGap()
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(comTipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(texNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(texTel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(texEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(datiLayout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton1)
                            .add(jButton2)))
                    .add(datiLayout.createSequentialGroup()
                        .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(chePrevVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(chePrevAcq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cheSolleciti, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cheOrdiVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cheOrdiAcq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cheDDTVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cheDDTAcq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cheFattVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cheFattAcq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(18, 18, 18)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(texNote, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butConferma)
                    .add(butAnnulla))
                .addContainerGap())
        );

        datiLayout.linkSize(new java.awt.Component[] {chePrevVen, jLabel5}, org.jdesktop.layout.GroupLayout.VERTICAL);

        getContentPane().add(dati, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConfermaActionPerformed
        try {
            //salvare i dati 
            dati.dbSave();
            JInternalFrameClientiFornitori parent = (JInternalFrameClientiFornitori) getParentFrame();
//            parent.caricaContatti();

            Integer id_row;
            if (dbStato.equals(tnxDbPanel.DB_INSERIMENTO)) {
                parent.contattiModel.addRow();
                id_row = parent.contattiModel.getRowCount()-1;
            } else {
                id_row = id_row_model;
            }
            DebugFastUtils.dump(dati.row);
            for (Object key : dati.row.keySet()) {
                System.out.println("key: " + key);
                parent.contattiModel.setValueAt(dati.row.get(key), id_row, parent.contattiModel.colonne.get(key));
            }
            
            parent.dati.dbForzaModificati();
            
        } catch (Exception e) {
            SwingUtils.showExceptionMessage(this, e);
        }
        
        try {
            setClosed(true);
        } catch (Exception e) {
            SwingUtils.showExceptionMessage(this, e);
        }
    }//GEN-LAST:event_butConfermaActionPerformed

    private void butAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnullaActionPerformed
        try {
            setClosed(true);
        } catch (Exception e) {
            SwingUtils.showExceptionMessage(this, e);
        }
    }//GEN-LAST:event_butAnnullaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<JCheckBox> list = getListCheckbox();
        for (JCheckBox c : list) {
            c.setSelected(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        List<JCheckBox> list = getListCheckbox();
        for (JCheckBox c : list) {
            c.setSelected(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnulla;
    private javax.swing.JButton butConferma;
    private tnxbeans.tnxCheckBox cheDDTAcq;
    private tnxbeans.tnxCheckBox cheDDTVen;
    private tnxbeans.tnxCheckBox cheFattAcq;
    private tnxbeans.tnxCheckBox cheFattVen;
    private tnxbeans.tnxCheckBox cheOrdiAcq;
    private tnxbeans.tnxCheckBox cheOrdiVen;
    private tnxbeans.tnxCheckBox chePrevAcq;
    private tnxbeans.tnxCheckBox chePrevVen;
    private tnxbeans.tnxCheckBox cheSolleciti;
    private tnxbeans.tnxComboField comTipo;
    private tnxbeans.tnxDbPanel dati;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private tnxbeans.tnxTextField texEmail;
    private tnxbeans.tnxTextField texNome;
    private tnxbeans.tnxMemoField texNote;
    private tnxbeans.tnxTextField texTel;
    // End of variables declaration//GEN-END:variables

    private void myinit() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) comTipo.getModel();
        model.addElement("");
        model.addElement("Principale");
        model.addElement("Amministrazione");
        model.addElement("Vendite");
        model.addElement("Acquisti");
        model.addElement("Tecnico");
        
        try {
            List list = dbu.getList(Db.getConn(), "select tipo from clie_forn_contatti where tipo not in ('Principale', 'Amministrazione', 'Vendite', 'Acquisti', 'Tecnico') group by tipo order by tipo");
            for (Object o : list) {
                if (StringUtils.isNotBlank(cu.s(o))) {
                    model.addElement(o);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        Vector v = new Vector();
        v.add("id");
        dati.dbChiave = v;
        dati.dbChiaveAutoInc = true;
        dati.dbNomeTabella = "clie_forn_contatti";
        dati.messaggio_nuovo_manuale = true;
        dati.edit_in_mem = true;
    }

    private List<JCheckBox> getListCheckbox() {
        List list = new ArrayList<JCheckBox>();
        list.add(chePrevVen);
        list.add(cheOrdiVen);
        list.add(cheDDTVen);
        list.add(cheFattVen);
        list.add(chePrevAcq);
        list.add(cheOrdiAcq);
        list.add(cheDDTAcq);
        list.add(cheFattAcq);        
        list.add(cheSolleciti);
        return list;
    }
    
    public void edit(int id, int id_row_model, Map row) {
        dbStato = tnxDbPanel.DB_MODIFICA;
        this.id_row_model = id_row_model;
        //dati.dbOpen(Db.getConn(), "select * from clie_forn_contatti where id = " + id);
        
        dati.row = row;
        dati.dbRefresh();
    }
    
    public void add() {
        dbStato = tnxDbPanel.DB_INSERIMENTO;
        dati.row = new HashMap();
        dati.dbRefresh();
    }
    
}
