/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.tnx.invoicex.gui;

import it.tnx.Db;
import it.tnx.commons.CastUtils;
import it.tnx.commons.SwingUtils;
import it.tnx.commons.cu;
import it.tnx.invoicex.InvoicexUtil;
import it.tnx.invoicex.Magazzino;
import net.sf.jasperreports.engine.JasperManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mceccarelli
 */
public class JInternalFrameReportEvadibile extends javax.swing.JInternalFrame {

    public JInternalFrameReportEvadibile() {
        initComponents();
        comListino.dbOpenList(Db.getConn(), "select descrizione, codice from tipi_listino where ricarico_flag is null or ricarico_flag != 'S'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butConferma = new javax.swing.JButton();
        comListino = new tnxbeans.tnxComboField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Report valore evadibile per Cliente");

        butConferma.setFont(butConferma.getFont().deriveFont(butConferma.getFont().getSize()+3f));
        butConferma.setText("Visualizza il Report");
        butConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfermaActionPerformed(evt);
            }
        });

        comListino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Listino:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("OBSOLETA");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 262, Short.MAX_VALUE)
                        .add(butConferma))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(comListino, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(comListino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                .add(jLabel2)
                .add(10, 10, 10)
                .add(butConferma)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConfermaActionPerformed
//
//        //controllo date
//        if (it.tnx.Checks.isDate(this.jTextField1.getText()) == false) {
//            javax.swing.JOptionPane.showInternalMessageDialog(this, "La data di partenza non e' valida !", "Attenzione", javax.swing.JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        if (it.tnx.Checks.isDate(this.jTextField2.getText()) == false) {
//            javax.swing.JOptionPane.showInternalMessageDialog(this, "La data di arrivo non e' valida !", "Attenzione", javax.swing.JOptionPane.WARNING_MESSAGE);
//            return;
//        }

        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        try {
            //aggiorno giacenze articoli
            InvoicexUtil.aggiornaGiacenzeArticoli();
            InvoicexUtil.aggiornaPrezziNettiUnitari(Db.getConn(), "righ_ordi", "test_ordi");

            //con compilazione
            //System.out.println("load jrxml");
            //JasperDesign jasperDesign = JasperManager.loadXmlDesign("/mnt/tnx/tnx/lavori/gianni/GestioneFatture/reports/stats_monthly.jrxml");
            //JasperDesign jasperDesign = JasperManager.loadXmlDesign("C:/cvs_tnx/tnx/Invoicex15/src/reports/stats_monthly.jrxml");
            //System.out.print("compilazione...");
            //JasperReport jasperReport = JasperManager.compileReport(jasperDesign);
            //System.out.println("...ok");
            //senza compilazione

            System.out.println("load jasper");
            JasperReport jasperReport = JasperManager.loadReport("reports/report_evadibile.jasper");

            // Second, create a map of parameters to pass to the report.
            java.util.Map parameters = new java.util.HashMap();
            parameters.put("listino", cu.toString(comListino.getSelectedKey()));
//            parameters.put("periodo", "Dal " + _this.jTextField1.getText() + " al " + _this.jTextField2.getText());
//            parameters.put("stampaDettagli", new Boolean(cheDettagli.isSelected()));
//            parameters.put("stampaQta", new Boolean(cheQta.isSelected()));

            java.sql.Connection conn = it.tnx.Db.getConn();
            JasperPrint jasperPrint = JasperManager.fillReport(jasperReport, parameters, conn);
            InvoicexUtil.apriStampa(jasperPrint);
        } catch (Exception err) {
            err.printStackTrace();
            SwingUtils.showExceptionMessage(this, err);
        }

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_butConfermaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butConferma;
    public tnxbeans.tnxComboField comListino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
