/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software � soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */



package it.tnx.commons.agg;


/*
 * JDialogChiusura.java
 *
 * Created on 17 novembre 2006, 8.57
 */

/**
 *
 * @author  mceccarelli
 */
public class JDialogProgress
    extends javax.swing.JDialog {
    public JDialogProgress() {
        super();
        initComponents();
    }

    /** Creates new form JDialogChiusura */
    public JDialogProgress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        labStatus.setFont(new java.awt.Font("Tahoma", 1, 11));
        labStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labStatus.setText("...");
        jPanel1.add(labStatus);
        labStatus.setBounds(10, 45, 300, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/commons/agg/view-refresh.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 15, 300, 22);

        progressbar.setIndeterminate(true);
        jPanel1.add(progressbar);
        progressbar.setBounds(10, 70, 300, 16);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogProgress(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labStatus;
    public javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables
}