package gestioneFatture;

import dnl.utils.text.table.MapBasedTableModel;
import dnl.utils.text.table.TextTable;
import it.tnx.Db;
import it.tnx.PrintUtilities;
import it.tnx.accessoUtenti.Permesso;
import it.tnx.commons.CastUtils;
import it.tnx.commons.DateUtils;
import it.tnx.commons.DbUtils;
import it.tnx.commons.DebugFastUtils;
import it.tnx.commons.FormatUtils;
import it.tnx.commons.HttpUtils;
import it.tnx.commons.MicroBench;
import it.tnx.commons.SwingUtils;
import it.tnx.commons.cu;
import it.tnx.commons.dbu;
import it.tnx.invoicex.InvoicexUtil;
import it.tnx.invoicex.Magazzino;
import it.tnx.invoicex.PlatformUtils;
import it.tnx.invoicex.data.Giacenza;
import it.tnx.shell.CurrentDir;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang.StringUtils;
import org.jdesktop.swingworker.SwingWorker;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JDialogManutenzione.java
 *
 * Created on 8-giu-2010, 11.07.31
 */
/**
 *
 * @author mceccarelli
 */
public class JDialogManutenzioneTest extends javax.swing.JDialog {

    String sql3 = "select m.id, m.data,m.causale, m.articolo, m.quantita, m.da_tabella, m.da_numero, m.da_anno, m.da_id from righ_ddt_acquisto r  "
            + " join movimenti_magazzino m on r.in_fatt = m.da_id and da_tabella = 'test_fatt_acquisto' "
            + " where in_fatt is not null";

    /**
     * Creates new form JDialogManutenzione
     */
    public JDialogManutenzioneTest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        butconverti = new javax.swing.JButton();
        forza = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        converti = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        text_storicizza = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        butStoricizza = new javax.swing.JButton();
        data_storicizzazione = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labErroreStoricizzazione = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        butRif = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaRif = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaNum = new javax.swing.JTextArea();
        jPanel20 = new javax.swing.JPanel();
        stampaNum = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        check_area = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta3 = new javax.swing.JTextArea();
        jPanel26 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaRicSca = new javax.swing.JTextArea();
        jPanel28 = new javax.swing.JPanel();
        butRif1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        butconverti2 = new javax.swing.JButton();
        butconverti3 = new javax.swing.JButton();
        tipo1 = new javax.swing.JComboBox();
        jPanel30 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        insart = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        locks = new javax.swing.JTextArea();
        jPanel32 = new javax.swing.JPanel();
        azzera_locks = new javax.swing.JButton();
        elenca_locks = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        azzeramag = new javax.swing.JTextArea();
        jPanel34 = new javax.swing.JPanel();
        butAzzera = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labErroreAzzera = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        logmysql51 = new javax.swing.JTextArea();
        jPanel36 = new javax.swing.JPanel();
        elenca_locks2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tabSbloccoFatture = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        logbloccasblocca = new javax.swing.JTextArea();
        jPanel38 = new javax.swing.JPanel();
        bloccoSblocco = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipo_doc = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        dal = new org.jdesktop.swingx.JXDatePicker();
        al = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenzione");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        butconverti.setText("Converti");
        butconverti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butconvertiActionPerformed(evt);
            }
        });

        forza.setText("forza");

        org.jdesktop.layout.GroupLayout jPanel13Layout = new org.jdesktop.layout.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .add(butconverti)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(forza)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butconverti)
                    .add(forza))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setLayout(new java.awt.BorderLayout());

        converti.setColumns(10);
        jScrollPane7.setViewportView(converti);

        jPanel14.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7, "card2");

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.BorderLayout());

        text_storicizza.setColumns(10);
        jScrollPane8.setViewportView(text_storicizza);

        jPanel15.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel15, java.awt.BorderLayout.CENTER);

        butStoricizza.setText("Storicizza");
        butStoricizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStoricizzaActionPerformed(evt);
            }
        });

        data_storicizzazione.setColumns(10);

        jLabel3.setText("alla data");

        labErroreStoricizzazione.setForeground(new java.awt.Color(255, 51, 0));

        org.jdesktop.layout.GroupLayout jPanel16Layout = new org.jdesktop.layout.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .add(butStoricizza)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(data_storicizzazione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel16Layout.createSequentialGroup()
                    .add(228, 228, 228)
                    .add(labErroreStoricizzazione)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butStoricizza)
                    .add(jLabel3)
                    .add(data_storicizzazione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel16Layout.createSequentialGroup()
                    .add(38, 38, 38)
                    .add(labErroreStoricizzazione)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel8, "card3");

        jPanel5.setLayout(new java.awt.BorderLayout());

        butRif.setText("Aggiorna i riferimenti");
        butRif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRifActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel17Layout = new org.jdesktop.layout.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .add(butRif)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .add(butRif)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        jPanel18.setLayout(new java.awt.BorderLayout());

        textAreaRif.setColumns(10);
        jScrollPane5.setViewportView(textAreaRif);

        jPanel18.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, "card4");

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.BorderLayout());

        textAreaNum.setColumns(10);
        jScrollPane4.setViewportView(textAreaNum);

        jPanel19.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel19, java.awt.BorderLayout.CENTER);

        stampaNum.setText("Stampa");
        stampaNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stampaNumActionPerformed(evt);
            }
        });

        jButton4.setText("Esegui il controllo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel20Layout = new org.jdesktop.layout.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stampaNum)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel20Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton4)
                    .add(stampaNum))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel20, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel4, "card5");

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel23.setLayout(new java.awt.BorderLayout());

        check_area.setEditable(false);
        check_area.setColumns(10);
        check_area.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(check_area);

        jPanel23.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel23, java.awt.BorderLayout.CENTER);

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel24Layout = new org.jdesktop.layout.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel24, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2, "card6");

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel25.setLayout(new java.awt.BorderLayout());

        ta3.setColumns(10);
        jScrollPane3.setViewportView(ta3);

        jPanel25.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel25, java.awt.BorderLayout.CENTER);

        jButton2.setText("controllo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("pulisci");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel26Layout = new org.jdesktop.layout.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel26, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3, "card7");

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel27.setLayout(new java.awt.BorderLayout());

        textAreaRicSca.setColumns(10);
        jScrollPane6.setViewportView(textAreaRicSca);

        jPanel27.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel27, java.awt.BorderLayout.CENTER);

        butRif1.setText("Ricalcola e aggiorna");
        butRif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRif1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel28Layout = new org.jdesktop.layout.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .add(butRif1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .add(butRif1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel28, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel6, "card8");

        jPanel9.setLayout(new java.awt.BorderLayout());

        butconverti2.setText("Anteprima");
        butconverti2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butconverti2ActionPerformed(evt);
            }
        });

        butconverti3.setText("Inserisci articoli");
        butconverti3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butconverti3ActionPerformed(evt);
            }
        });

        tipo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fatture di Vendita", "Fatture di Acquisto", "DDT di Vendita", "DDT di Acquisto", "Preventivi/Ordini di Vendita", "Preventivi/Ordini di Acquisto" }));
        tipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel29Layout = new org.jdesktop.layout.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .add(tipo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(butconverti2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(butconverti3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel29Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tipo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(butconverti2)
                    .add(butconverti3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel29, java.awt.BorderLayout.PAGE_START);

        jPanel30.setLayout(new java.awt.BorderLayout());

        insart.setColumns(10);
        insart.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane9.setViewportView(insart);

        jPanel30.add(jScrollPane9, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel30, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9, "card9");

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel31.setLayout(new java.awt.BorderLayout());

        locks.setColumns(10);
        locks.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane10.setViewportView(locks);

        jPanel31.add(jScrollPane10, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel31, java.awt.BorderLayout.CENTER);

        azzera_locks.setText("Azzera");
        azzera_locks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azzera_locksActionPerformed(evt);
            }
        });

        elenca_locks.setText("Elenca locks");
        elenca_locks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elenca_locksActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel32Layout = new org.jdesktop.layout.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .add(elenca_locks)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(azzera_locks)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel32Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(elenca_locks)
                    .add(azzera_locks))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel32, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel10, "card10");

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel33.setLayout(new java.awt.BorderLayout());

        azzeramag.setColumns(10);
        azzeramag.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane11.setViewportView(azzeramag);

        jPanel33.add(jScrollPane11, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel33, java.awt.BorderLayout.CENTER);

        butAzzera.setText("Azzera");
        butAzzera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAzzeraActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliccando Azzera verranno generati i movimenti di magazzino necessari per azzerare le giacenze");

        labErroreAzzera.setForeground(new java.awt.Color(255, 51, 0));

        org.jdesktop.layout.GroupLayout jPanel34Layout = new org.jdesktop.layout.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel34Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(butAzzera)
                    .add(jLabel4))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel34Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel34Layout.createSequentialGroup()
                    .add(79, 79, 79)
                    .add(labErroreAzzera)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(butAzzera)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel34Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel34Layout.createSequentialGroup()
                    .add(48, 48, 48)
                    .add(labErroreAzzera)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel11.add(jPanel34, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel11, "card11");

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel35.setLayout(new java.awt.BorderLayout());

        logmysql51.setColumns(10);
        logmysql51.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane12.setViewportView(logmysql51);

        jPanel35.add(jScrollPane12, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel35, java.awt.BorderLayout.CENTER);

        elenca_locks2.setText("Scarica");
        elenca_locks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elenca_locks2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Clicca qui per scaricare mysql 5.1 interno solo per windows");

        org.jdesktop.layout.GroupLayout jPanel36Layout = new org.jdesktop.layout.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel36Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(elenca_locks2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(elenca_locks2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel36, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel12, "card12");

        tabSbloccoFatture.setLayout(new java.awt.BorderLayout());

        jPanel37.setLayout(new java.awt.BorderLayout());

        logbloccasblocca.setColumns(10);
        jScrollPane13.setViewportView(logbloccasblocca);

        jPanel37.add(jScrollPane13, java.awt.BorderLayout.CENTER);

        tabSbloccoFatture.add(jPanel37, java.awt.BorderLayout.CENTER);

        bloccoSblocco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blocca", "Sblocca" }));

        jLabel6.setText("Lavoro:");

        jLabel7.setText("Tipo documento:");

        tipo_doc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tutti", "Fatture di acquisto", "Fatture di vendita" }));

        jLabel8.setText("Dal");

        dal.setName("dal"); // NOI18N
        dal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dalFocusLost(evt);
            }
        });
        dal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dalActionPerformed(evt);
            }
        });
        dal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dalPropertyChange(evt);
            }
        });

        al.setName("dal"); // NOI18N
        al.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alFocusLost(evt);
            }
        });
        al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alActionPerformed(evt);
            }
        });
        al.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                alPropertyChange(evt);
            }
        });

        jLabel9.setText("Al");

        btnStart.setText("Inzia operazione");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel38Layout = new org.jdesktop.layout.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel38Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel38Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bloccoSblocco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tipo_doc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnStart))
                .add(18, 18, 18)
                .add(jPanel38Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel38Layout.createSequentialGroup()
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel38Layout.createSequentialGroup()
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(al, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel38Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel38Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel6)
                        .add(bloccoSblocco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel7)
                        .add(tipo_doc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel8))
                    .add(dal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel38Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnStart)
                    .add(jPanel38Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel9)
                        .add(al, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSbloccoFatture.add(jPanel38, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(tabSbloccoFatture, "card13");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("jToggleButton1");

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("jToggleButton2");

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("jToggleButton3");

        org.jdesktop.layout.GroupLayout jPanel21Layout = new org.jdesktop.layout.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel21Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jPanel21Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jToggleButton3)
                    .add(jToggleButton2)
                    .add(jToggleButton1))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel21Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jToggleButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToggleButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToggleButton3)
                .addContainerGap())
        );

        getContentPane().add(jPanel21, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
//            main.fileIni.setValue("varie", "manutenzione_sel_index", tabpadre.getSelectedIndex());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void butconvertiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butconvertiActionPerformed
        SwingWorker w = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                //prima di tutto controllo se è già in utf8 dalla tabella clie_forn
                Connection conn = null;
                try {
                    conn = Db.getConn();
                    DbUtils.tryExecQuery(conn, "SET FOREIGN_KEY_CHECKS = 0;");

                    List<Map> ret = DbUtils.getListMap(conn, "show table status where name = 'clie_forn'");
                    String coll = cu.s(ret.get(0).get("Collation"));
                    if (!forza.isSelected() && coll.equalsIgnoreCase("utf8_general_ci")) {
                        converti.append("la tabella clie_forn è già UTF8 quindi non procedo (collate:" + coll + ")" + "\n");
                        return null;
                    }

                    //prendo elenco tabelle e converto in utf8
                    ret = DbUtils.getListMap(conn, "show table status");
                    for (Map r : ret) {
                        String tab = cu.s(r.get("Name"));
                        coll = cu.s(r.get("Collation"));
                        if (StringUtils.isNotBlank(coll)) {
                            //controllo che non sia utf8
                            if (!coll.equalsIgnoreCase("utf8_general_ci")) {
                                //faccio backup
                                //prima faccio dump
                                File dirbackuputf8 = new File(CurrentDir.getCurrentDir() + "/backup_conv_utf8");
                                if (dirbackuputf8.isDirectory() || dirbackuputf8.mkdir()) {
                                    String nomeFileDump = CurrentDir.getCurrentDir() + "/backup_conv_utf8/dump_";
                                    SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmm");
                                    Date d = new Date();
                                    String name = tab;
                                    nomeFileDump += name + "_" + sdf.format(d) + ".txt";
                                    FileOutputStream fos = new FileOutputStream(nomeFileDump, false);
                                    it.tnx.Util.dumpTable(name, conn, fos);
                                    System.out.println(name + " : dumped");
                                    fos.close();
                                    //converto
                                    converti.append("conversione " + tab + " : " + coll + "\n");
                                    try {
                                        String sql = "ALTER TABLE " + tab + " CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci";
                                        System.out.println("sql = " + sql);
                                        DbUtils.tryExecQuery(conn, sql);
                                    } catch (Exception e) {
                                        converti.append(e.toString() + "\n");
                                    }
                                } else {
                                    converti.append("errore cartella " + dirbackuputf8.getAbsolutePath() + "\n");
                                    break;
                                }
                            } else {
                                converti.append("non converto " + tab + " perchè già utf8\n");
                            }
                        } else {
                            converti.append("non converto " + tab + " perchè non tabella\n");
                        }
                        converti.setCaretPosition(converti.getText().length());
                    }

                    ret = DbUtils.getListMap(conn, "show table status");
                    for (Map r : ret) {
                        String tab = cu.s(r.get("Name"));
                        coll = cu.s(r.get("Collation"));
                        converti.append("verifica " + tab + " : " + coll + "\n");
                        converti.setCaretPosition(converti.getText().length());
                    }

                    //converto db
                    DbUtils.tryExecQuery(conn, "ALTER DATABASE " + Db.dbNameDB + " COLLATE 'utf8_general_ci'");

                    //verifico db
                    ret = DbUtils.getListMap(conn, "show variables like 'collation_database'");
                    converti.append("verifica " + Db.dbNameDB + " : " + ret.get(0).get("Value") + "\n");

                } catch (Exception e2) {
                    e2.printStackTrace();
                    converti.append(e2.toString() + "\n");
                }

                try {
                    DbUtils.tryExecQuery(conn, "SET FOREIGN_KEY_CHECKS = 1;");
                } catch (Exception e) {
                }
                return null;
            }
        };
        w.execute();
    }//GEN-LAST:event_butconvertiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String msg = "";
        MicroBench mb = new MicroBench();
        mb.start();
        String msgf = main.controlloNumeri("test_fatt");
        String msgd = main.controlloNumeri("test_ddt");
        System.out.println("fine controllo numerazione tempo:" + mb.getDiff(""));
        if (StringUtils.isNotBlank(msgf) || StringUtils.isNotBlank(msgd)) {
            msg = "Attenzione, problemi nella numerazione dei documenti:\n";
            if (StringUtils.isNotBlank(msgf)) {
                msg += "\nFatture di vendita:\n" + msgf;
            }
            if (StringUtils.isNotBlank(msgd)) {
                msg += "\nDDT di vendita:\n" + msgd;
            }
            textAreaNum.setText(msg);
        } else {
            textAreaNum.setText("Numerazione corretta");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void stampaNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stampaNumActionPerformed
        PrintUtilities p = new PrintUtilities(textAreaNum);
        p.scala = 1;
        p.print();
    }//GEN-LAST:event_stampaNumActionPerformed

    private void butRifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRifActionPerformed
        String msg = "";
        MicroBench mb = new MicroBench();
        mb.start();

        SwingUtils.mouse_wait(this);

        aggiornaRif(false);
        aggiornaRif(true);

        SwingUtils.mouse_def(this);

        mb.out("fine rif");
    }//GEN-LAST:event_butRifActionPerformed

    private void butStoricizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStoricizzaActionPerformed
        Connection conn = null;

        Date data_stor = new Date();
        String s_data_stor = DateUtils.formatDateTime(data_stor);
        String s_data_stor_mysql = FormatUtils.formatMysqlTimestamp(data_stor);

        int progress = 0;

        try {
            //            conn = Db.getConnection();
            conn = Db.getConn();

            //calcolare le giacenze e inserire movimenti di esistenza iniziale
            Date data = cu.toDateIta(data_storicizzazione.getText());
            String s_data = DateUtils.formatDateIta(data);
            List<Giacenza> ret = main.magazzino.getGiacenza(true, null, (Integer) 5, data, true, false, false, Magazzino.Depositi.TUTTI_DETTAGLIO);

            dbu.tryExecQuery(conn, "LOCK TABLES storicizzazioni WRITE"
                    + ", movimenti_magazzino WRITE"
                    + ", movimenti_magazzino_storico WRITE"
                    + "");
            progress = 1;

            //creo record storicizzazione
            String sql = "insert into storicizzazioni set tabella = 'movimenti_magazzino', inizio = '" + s_data_stor_mysql + "'";
            DbUtils.tryExecQuery(conn, sql);
            Integer id_stor = cu.i(dbu.getObject(conn, "select LAST_INSERT_ID()"));
            progress = 2;

            Integer ultimo_id_mov = cu.i0(dbu.getObject(conn, "select max(id) from movimenti_magazzino"));

            //scrivo i movimenti di es iniz sulla base della giacenza
            for (Iterator<Giacenza> it = ret.iterator(); it.hasNext();) {
                Giacenza g = it.next();
                //                System.out.println("g = " + g);
                Map m = new HashMap();
                m.put("data", data);
                m.put("causale", 1);
                m.put("deposito", g.getDeposito_id() == null ? 0 : g.getDeposito_id());
                m.put("articolo", g.getCodice_articolo());
                m.put("quantita", g.getGiacenza());
                m.put("note", "storicizzazione del " + s_data_stor + " a data " + s_data);
                m.put("matricola", StringUtils.isBlank(g.getMatricola()) ? null : g.getMatricola());
                m.put("lotto", StringUtils.isBlank(g.getLotto()) ? null : g.getLotto());
                m.put("id_storicizzazione", id_stor);
                sql = "insert into movimenti_magazzino set " + dbu.prepareSqlFromMap(m);
                DbUtils.tryExecQuery(conn, sql);
            }
            progress = 4;

            //sposto i movimenti da storicizzare, vado di 1000 in 1000
            int tot = cu.i0(dbu.getObject(conn, "select count(*) from movimenti_magazzino where data <= " + Db.pc(data, Types.DATE) + " and id <= " + ultimo_id_mov));
            System.out.println("mov da spostare = " + tot);

            sql = "insert into movimenti_magazzino_storico "
                    + " select id, data, causale, deposito, articolo, quantita, note, "
                    + " da_tabella, da_serie, da_numero, da_anno, matricola, da_id, lotto, da_tipo_fattura, "
                    + " modificato_ts, prezzo_medio, da_id_riga, " + id_stor + " as id_stor from movimenti_magazzino where data <= " + Db.pc(data, Types.DATE) + " and id <= " + ultimo_id_mov;
            int ret_tot = DbUtils.tryExecQueryWithResult(conn, sql);
            System.out.println("mov spostati = " + ret_tot);

            progress = 5;

            text_storicizza.setText("movimenti storicizzati: " + ret_tot);

            sql = "delete from movimenti_magazzino where data <= " + Db.pc(data, Types.DATE) + " and id <= " + ultimo_id_mov;
            int ret_tot_del = DbUtils.tryExecQueryWithResult(conn, sql);

            progress = 6;

            sql = "update storicizzazioni set fine = '" + FormatUtils.formatMysqlTimestamp(new Date()) + "' where id = " + id_stor;
            DbUtils.tryExecQuery(conn, sql);

            progress = 7;

            System.out.println("mov spostati del = " + ret_tot_del);
            text_storicizza.setText("movimenti storicizzati: " + ret_tot + "/" + ret_tot_del);

            dbu.tryExecQuery(conn, "UNLOCK TABLES");
            progress = 8;

            //azzero mov eliminati
            sql = "delete from movimenti_magazzino_eliminati";
            DbUtils.tryExecQuery(conn, sql);
        } catch (Exception e) {
            SwingUtils.showExceptionMessage(this, e);
            e.printStackTrace();
            System.out.println("annullare la storicizzazione, bloccata al punto: " + progress);
            SwingUtils.showErrorMessage(this, "annullare la storicizzazione, bloccata al punto: " + progress);
            try {
                dbu.tryExecQuery(conn, "UNLOCK TABLES");
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
        if (conn != null) {
            try {
                conn.close();
            } catch (Exception e) {
            }
        }
        System.out.println("fine storicizzazione");
    }//GEN-LAST:event_butStoricizzaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet r = null;
        try {
            r = DbUtils.tryOpenResultSet(Db.getConn(), "show tables");
            while (r.next()) {
                check_area.append(r.getString(1));
                ResultSet rc = DbUtils.tryOpenResultSet(Db.getConn(), "check table " + r.getString(1));
                try {
                    rc.next();
                    System.out.println(rc.getString(4));
                    System.out.println(r.getString(1) + " : checked");
                    check_area.append(" ..." + rc.getString(4) + "\n");
                    check_area.setCaretPosition(check_area.getText().length());
                } finally {
                    rc.getStatement().close();
                    rc.close();
                }
            }
        } catch (Exception err) {
            try {
                r.getStatement().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                r.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ta3.append("\npulizia:\n");
        ta3.append("sql:\n" + sql3);
        List<Map> list;
        try {
            list = DbUtils.getListMap(Db.getConn(), sql3);
            for (Map m : list) {
                ta3.append("\nrec: " + DebugFastUtils.dumpAsString(m));
                String sql = "delete from movimenti_magazzino where id = " + CastUtils.toString(m.get("id"));
                ta3.append("\nsql: " + DebugFastUtils.dumpAsString(m));
                int recs = DbUtils.tryExecQueryWithResult(Db.getConn(), sql);
                ta3.append("\nrecs affected: " + recs);
                ta3.append("\n");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            SwingUtils.showErrorMessage(main.getPadreWindow(), ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ta3.append("sql:\n" + sql3);
        List<Map> list;
        try {
            list = DbUtils.getListMap(Db.getConn(), sql3);
            for (Map m : list) {
                ta3.append("\nrec: " + DebugFastUtils.dumpAsString(m));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            SwingUtils.showErrorMessage(main.getPadreWindow(), ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo1ActionPerformed
        main.fileIni.setValue("pref", "manutenzione_import_articoli_tipo1", tipo1.getSelectedIndex());
    }//GEN-LAST:event_tipo1ActionPerformed

    private void butconverti3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butconverti3ActionPerformed

    }//GEN-LAST:event_butconverti3ActionPerformed

    private void butconverti2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butconverti2ActionPerformed

    }//GEN-LAST:event_butconverti2ActionPerformed

    private void butRif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRif1ActionPerformed
        try {
            textAreaRicSca.append("records aggiornati per totali: " + InvoicexUtil.ricalcolaPagatoDaPagare());
            textAreaRicSca.append("\nrecords aggiornati per numeri: " + InvoicexUtil.ricalcolaTotaleScadenze());
        } catch (Exception e) {
            e.printStackTrace();
            textAreaRicSca.append(e.toString());
        }
    }//GEN-LAST:event_butRif1ActionPerformed

    private void butAzzeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAzzeraActionPerformed
        Magazzino m = new Magazzino();
        ArrayList list;

        Integer deposito_default = 0;
        boolean is_deposito_singolo = true;

        try {
            list = m.getGiacenza(true, null, (Integer) 5, null, true, false, false, Magazzino.Depositi.TUTTI_DETTAGLIO);
            is_deposito_singolo = Magazzino.isMultiDeposito();

            if (is_deposito_singolo) {
                // Recupero deposito di default
                deposito_default = CastUtils.toInteger(main.fileIni.getValue("depositi", "predefinito", "0"));

                if (SwingUtils.showYesNoMessage(this, "Proseguendo tutti i movimenti verranno spostati sul magazzino di default. Vuoi proseguire?", "")) {
                    DbUtils.tryExecQuery(Db.getConn(), "UPDATE movimenti_magazzino SET deposito = '" + Db.pc(deposito_default, Types.INTEGER) + "'");
                } else {
                    return;
                }
            }

        } catch (Exception ex) {
            SwingUtils.showExceptionMessage(this, ex);
            return;
        }
        for (Object o : list) {
            Giacenza g = ((Giacenza) o);
            Integer causale = null;
            String msg = g.getCodice_articolo() + (g.getDeposito_id() == null ? "" : " (DEPOSITO: " + g.getDeposito_id() + ")") + ":" + g.getGiacenza() + " -> ";
            if (g.getGiacenza() > 0) {
                msg += "scarico";
                causale = Magazzino.SCARICO;
            } else if (g.getGiacenza() < 0) {
                msg += "carico";
                causale = Magazzino.CARICO;
            } else {
                msg += "niente, già a 0";
            }
            azzeramag.append(msg + "\n");
            System.out.println(msg);
            Map r = new HashMap();
            r.put("data", new Date());
            r.put("causale", causale);
            r.put("deposito", main.fileIni.getValue("depositi", "predefinito", "0"));
            r.put("articolo", g.getCodice_articolo());
            r.put("quantita", Math.abs(g.getGiacenza()));
            r.put("note", "azzeramento magazzino");
            r.put("deposito", g.getDeposito_id() == null ? 0 : g.getDeposito_id());

            String sql = "insert into movimenti_magazzino set " + dbu.prepareSqlFromMap(r);
            System.out.println("sql = " + sql);
            try {
                dbu.tryExecQuery(Db.getConn(), sql);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_butAzzeraActionPerformed

    private void elenca_locksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elenca_locksActionPerformed
        try {
            List<Map> list = dbu.getListMap(Db.getConn(), "select * from locks");
            if (list == null || list.size() == 0) {
                locks.setText("nessun lock presente");
            } else {
                TextTable tt = new TextTable(new MapBasedTableModel(list));
                tt.setAddRowNumbering(true);
                ByteArrayOutputStream byteout = new ByteArrayOutputStream();
                PrintStream ps = new PrintStream(byteout);
                tt.printTable(ps, 0);
                locks.setText(byteout.toString() + "\n");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_elenca_locksActionPerformed

    private void azzera_locksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azzera_locksActionPerformed
        if (SwingUtils.showYesNoMessage(this, "Sicuro di azzerare i locks ?")) {
            String sql = "delete from locks";
            System.out.println("locks elimino locks sql = " + sql);
            try {
                dbu.tryExecQuery(Db.getConn(), sql);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_azzera_locksActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        logbloccasblocca.setText("");

        String data_dal = DateUtils.formatDateIta(dal.getDate());
        String data_al = DateUtils.formatDateIta(al.getDate());
        String lavoro = String.valueOf(bloccoSblocco.getSelectedItem());
        String tipoDoc = String.valueOf(tipo_doc.getSelectedItem());

        if (data_dal != "" && data_al != "") {
            System.out.println("Data dal: " + data_dal);
            System.out.println("Data al: " + data_al);
            System.out.println("Tipo di operazione: " + lavoro);
            System.out.println("Tipi di documento: " + tipoDoc);

            ArrayList<String> query = new ArrayList();

            if (tipoDoc == "Tutti" || tipoDoc == "Fatture di acquisto") {
                String q = "SELECT id, serie, numero, anno, tipo_fattura, 'test_fatt_acquisto' as tabella "
                + "FROM test_fatt_acquisto "
                + "WHERE data BETWEEN " + Db.pc(data_dal, Types.DATE) + " AND " + Db.pc(data_al, Types.DATE);

                if (lavoro == "Blocca") {
                    q += " AND isNull(bloccata)";
                } else {
                    q += "AND (!isNull(bloccata) OR bloccata = '' OR bloccata = '0000-00-00')";
                }

                query.add(q);
            }

            if (tipoDoc == "Tutti" || tipoDoc == "Fatture di vendita") {
                String q = "SELECT id, serie, numero, anno, tipo_fattura, 'test_fatt' as tabella "
                + "FROM test_fatt "
                + "WHERE data BETWEEN " + Db.pc(data_dal, Types.DATE) + " AND " + Db.pc(data_al, Types.DATE);

                if (lavoro == "Blocca") {
                    q += " AND isNull(bloccata)";
                } else {
                    q += "AND (!isNull(bloccata) OR bloccata = '' OR bloccata = '0000-00-00')";
                }

                query.add(q);
            }

            String sql = StringUtils.join(query, " UNION ");
            try {

                ArrayList<Map> lista = dbu.getListMap(Db.getConn(), sql);
                int rowCount = lista.size();

                logbloccasblocca.append(rowCount + " documenti da elaborare" + System.getProperty("line.separator"));
                logbloccasblocca.append(System.getProperty("line.separator"));

                if (rowCount > 0) {
                    for (Map record : lista) {

                        Integer id = CastUtils.toInteger(record.get("id"));
                        Integer tipodoc = CastUtils.toInteger(record.get("tipo_fattura"));
                        String seriedoc = CastUtils.toString(Db.nz(record.get("serie"), ""));
                        String numerodoc = CastUtils.toString(record.get("numero"));
                        String annodoc = CastUtils.toString(record.get("anno"));
                        String tabella = CastUtils.toString(record.get("tabella"));
                        String tipoFattura = dbFattura.getDescTipoFattura(tipodoc);

                        String descrizione = seriedoc + numerodoc + "/" + annodoc;

                        String operazione = lavoro == "Blocca" ? "bloccata" : "sbloccata";
                        String value = lavoro == "Blocca" ? "CURRENT_DATE" : "null";

                        String update = "UPDATE " + tabella + " SET bloccata = " + value + " WHERE id = " + Db.pc(id, Types.INTEGER);

                        Db.executeSql(update);

                        logbloccasblocca.append(tipoFattura + " " + descrizione + " " + operazione + System.getProperty("line.separator"));
                    }

                    logbloccasblocca.append(System.getProperty("line.separator") + rowCount + " documenti elaborati");
                }

            } catch (Exception ex) {
                Logger.getLogger(JDialogManutenzioneTest.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            logbloccasblocca.setText("Devi selezionare una data di inizio e fine per attivare l'operazione");

        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void alPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_alPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_alPropertyChange

    private void alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alActionPerformed

    private void alFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_alFocusLost

    private void dalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dalPropertyChange
        System.out.println("evt = " + evt);
    }//GEN-LAST:event_dalPropertyChange

    private void dalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dalActionPerformed

    }//GEN-LAST:event_dalActionPerformed

    private void dalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dalFocusLost

    }//GEN-LAST:event_dalFocusLost

    private void elenca_locks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elenca_locks2ActionPerformed
        if (PlatformUtils.isWindows()) {

            if (!SwingUtils.showYesNoMessage(this, "Attenzione, devo stoppare mysql interno, procedo ?\nSe hai finestra di Invoicex aperte magari prima chiudile")) {
                return;
            }

            SwingUtils.mouse_wait(this);
            SwingWorker w = new SwingWorker() {

                @Override
                protected Object doInBackground() throws Exception {
                    //copio il binario di mysql
                    Date d = new Date();
                    SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy_MM_dd_HH_mm_ss");

                    try {
                        logmysql51.append("\ncopio mysql\\bin\\mysqld-nt.exe in mysqld-nt_" + sdf1.format(d) + ".exe");
                        FileUtils.copyFile(new File("mysql\\bin\\mysqld-nt.exe"), new File("mysql\\bin\\mysqld-nt_" + sdf1.format(d) + ".exe"));

                        logmysql51.append("\ncopio mysql\\bin\\mysqladmin.exe ...");
                        FileUtils.copyFile(new File("mysql\\bin\\mysqladmin.exe"), new File("mysql\\bin\\mysqladmin_" + sdf1.format(d) + ".exe"));

                        logmysql51.append("\ncopio mysql\\share\\english\\errmsg.sys ...");
                        FileUtils.copyFile(new File("mysql\\share\\english\\errmsg.sys"), new File("mysql\\share\\english\\errmsg_" + sdf1.format(d) + ".sys"));
                        logmysql51.append("\ncopio mysql\\share\\english\\errmsg.txt ...");
                        FileUtils.copyFile(new File("mysql\\share\\english\\errmsg.txt"), new File("mysql\\share\\english\\errmsg_" + sdf1.format(d) + ".txt"));

                        logmysql51.append("\ncopio mysql\\share\\italian\\errmsg.sys ...");
                        FileUtils.copyFile(new File("mysql\\share\\italian\\errmsg.sys"), new File("mysql\\share\\italian\\errmsg_" + sdf1.format(d) + ".sys"));
                        logmysql51.append("\ncopio mysql\\share\\italian\\errmsg.txt ...");
                        FileUtils.copyFile(new File("mysql\\share\\italian\\errmsg.txt"), new File("mysql\\share\\italian\\errmsg_" + sdf1.format(d) + ".txt"));

                    } catch (Exception e) {
                        logmysql51.append("\n\n" + e.toString());
                        e.printStackTrace();
                    }

                    //stoppo mysql
                    logmysql51.append("\nattendo chiusura mysql interno");
                    main.stopdb(false);
                    while (main.mysql_is_running) {
                        Thread.sleep(1000);
                        logmysql51.append(".");
                    }

                    //scarico il nuovo
                    logmysql51.append("\nscarico mysql_51_win.zip...");
                    HttpUtils.saveBigFile("http://server.invoicex.it/download/invoicex/mysql/mysql_51_win.zip", "mysql_51_win.zip");

                    //scompatto
                    logmysql51.append("\nscompatto...");
                    UnZip.unzip(new File("mysql_51_win.zip"), new File("."));

                    logmysql51.append("\n\n\nFinito !!!\nControlla nella cartella mysql\\bin e riavvia Invoicex");

                    return null;
                }

                @Override
                protected void done() {
                    SwingUtils.mouse_def(JDialogManutenzioneTest.this);
                }

            };
            w.execute();
        } else {
            SwingUtils.showErrorMessage(this, "Sei su " + PlatformUtils.getPlatformName() + " !!!");
        }
    }//GEN-LAST:event_elenca_locks2ActionPerformed

    public void aggiornaRif(boolean acquisto) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception err) {
                }

                JDialogManutenzioneTest dialog = new JDialogManutenzioneTest(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker al;
    private javax.swing.JButton azzera_locks;
    private javax.swing.JTextArea azzeramag;
    private javax.swing.JComboBox bloccoSblocco;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton butAzzera;
    private javax.swing.JButton butRif;
    private javax.swing.JButton butRif1;
    private javax.swing.JButton butStoricizza;
    private javax.swing.JButton butconverti;
    private javax.swing.JButton butconverti2;
    private javax.swing.JButton butconverti3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea check_area;
    private javax.swing.JTextArea converti;
    private org.jdesktop.swingx.JXDatePicker dal;
    private javax.swing.JTextField data_storicizzazione;
    private javax.swing.JButton elenca_locks;
    private javax.swing.JButton elenca_locks2;
    private javax.swing.JCheckBox forza;
    private javax.swing.JTextArea insart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel labErroreAzzera;
    private javax.swing.JLabel labErroreStoricizzazione;
    private javax.swing.JTextArea locks;
    private javax.swing.JTextArea logbloccasblocca;
    private javax.swing.JTextArea logmysql51;
    private javax.swing.JButton stampaNum;
    private javax.swing.JTextArea ta3;
    private javax.swing.JPanel tabSbloccoFatture;
    private javax.swing.JTextArea textAreaNum;
    private javax.swing.JTextArea textAreaRicSca;
    private javax.swing.JTextArea textAreaRif;
    private javax.swing.JTextArea text_storicizza;
    private javax.swing.JComboBox tipo1;
    private javax.swing.JComboBox tipo_doc;
    // End of variables declaration//GEN-END:variables

}
