/**
 * Invoicex
 * Copyright (c) 2005-2016 Marco Ceccarelli, Tnx srl
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */



package gestioneFatture;

import tnxbeans.LimitedTextPlainDocument;


/*
 * JDialogChiusura.java
 *
 * Created on 17 novembre 2006, 8.57
 */

/**
 *
 * @author  mceccarelli
 */
public class JDialogSelezionaSerie
    extends javax.swing.JDialog {

    public String serie = "";
    
    public JDialogSelezionaSerie() {
        super();
        initComponents();

        LimitedTextPlainDocument limit = new LimitedTextPlainDocument(1, true);
        texSerie.setDocument(limit);
    }

    /** Creates new form JDialogChiusura */
    public JDialogSelezionaSerie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        LimitedTextPlainDocument limit = new LimitedTextPlainDocument(1, true);
        texSerie.setDocument(limit);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        texSerie = new javax.swing.JTextField();
        brnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+1f));
        jLabel1.setText("Inserisci la serie del documento di destinazione:");

        texSerie.setColumns(2);
        texSerie.setFont(texSerie.getFont().deriveFont(texSerie.getFont().getSize()+1f));
        texSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texSerieActionPerformed(evt);
            }
        });
        texSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texSerieKeyTyped(evt);
            }
        });

        brnConferma.setFont(brnConferma.getFont().deriveFont(brnConferma.getFont().getSize()+1f));
        brnConferma.setText("Conferma");
        brnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnConfermaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(texSerie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(brnConferma)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(texSerie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(brnConferma)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnConfermaActionPerformed
        this.serie = texSerie.getText();
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_brnConfermaActionPerformed

    private void texSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texSerieActionPerformed
        brnConfermaActionPerformed(null);
    }//GEN-LAST:event_texSerieActionPerformed

    private void texSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texSerieKeyTyped
        texSerie.setText(texSerie.getText().toUpperCase());
    }//GEN-LAST:event_texSerieKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogSelezionaSerie(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnConferma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField texSerie;
    // End of variables declaration//GEN-END:variables
}