/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioneFatture;

import it.tnx.commons.SwingUtils;
import it.tnx.commons.cu;
import it.tnx.commons.dbu;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Marco
 */
public class JDialogNomiFilePdf extends javax.swing.JDialog {

    /**
     * Creates new form JDialogNomiFilePdf
     */
    public JDialogNomiFilePdf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //init
        tab.setValueAt(Db.TIPO_DOCUMENTO_ORDINE, 0, 0);
        tab.setValueAt("ORDINE", 0, 1);
        tab.setValueAt("Ordine", 0, 2);
        tab.setValueAt("Order", 0, 3);
        tab.setValueAt(Db.TIPO_DOCUMENTO_PREVENTIVO, 1, 0);
        tab.setValueAt("PREVENTIVO", 1, 1);
        tab.setValueAt("Preventivo", 1, 2);
        tab.setValueAt("Quote", 1, 3);
        tab.setValueAt(Db.TIPO_DOCUMENTO_DDT, 2, 0);
        tab.setValueAt("DDT", 2, 1);
        tab.setValueAt("DDT", 2, 2);
        tab.setValueAt("Delivery_note", 2, 3);
        tab.setValueAt(Db.TIPO_FATTURA_IMMEDIATA, 3, 0);
        tab.setValueAt("FATTURA", 3, 1);
        tab.setValueAt("Fattura", 3, 2);
        tab.setValueAt("Invoice", 3, 3);
        tab.setValueAt(Db.TIPO_FATTURA_ACCOMPAGNATORIA, 4, 0);
        tab.setValueAt("FATTURA ACCOMPAGNATORIA", 4, 1);
        tab.setValueAt("Fattura", 4, 2);
        tab.setValueAt("Invoice", 4, 3);
        tab.setValueAt(Db.TIPO_FATTURA_PROFORMA, 5, 0);
        tab.setValueAt("FATTURA PROFORMA", 5, 1);
        tab.setValueAt("Fattura_PROFORMA", 5, 2);
        tab.setValueAt("PROFORMA_Invoice", 5, 3);
        tab.setValueAt(Db.TIPO_FATTURA_NOTA_DI_CREDITO, 6, 0);
        tab.setValueAt("NOTA DI CREDITO", 6, 1);
        tab.setValueAt("Nota_di_credito", 6, 2);
        tab.setValueAt("Credit_note", 6, 3);

        try {
            String ret = cu.s(dbu.getObject(Db.getConn(), "select nomi_pdf from dati_azienda", false));
            JSONParser p = new JSONParser();
            JSONArray ja = (JSONArray) p.parse(ret);
            System.out.println("ja = " + ja);
            for (Object o : ja) {
                JSONObject jo = (JSONObject)o;
                for (int r = 0; r < tab.getRowCount(); r++) {
                    if (jo.get("ID").equals(tab.getValueAt(r, 0))) {
                        tab.setValueAt(jo.get("Nome Italiano"), r, 2);
                        tab.setValueAt(jo.get("Nome Inglese"), r, 3);
                        break;
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Nome Italiano", "Nome Inglese"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setMinWidth(0);
            tab.getColumnModel().getColumn(0).setPreferredWidth(0);
            tab.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jButton1.setText("Conferma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annulla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Puoi impostare il nome del file sotto a 'Nome Italiano' e 'Nome Inglese' per la creazione dei pdf");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            List<Map> list = dbu.getListMapFromTableModel(tab.getModel());
            System.out.println("list = " + list);
            String json = JSONValue.toJSONString(list);
            System.out.println("json = " + json);
            dbu.tryExecQuery(Db.getConn(), "update dati_azienda set nomi_pdf = " + dbu.sql(json));
            dispose();
        } catch (Exception e) {
            e.printStackTrace();
            SwingUtils.showExceptionMessage(this, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogNomiFilePdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogNomiFilePdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogNomiFilePdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogNomiFilePdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogNomiFilePdf dialog = new JDialogNomiFilePdf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
